### ISSUE TITLE
The Code Usage and its Official Acceptance.

### ISSUE THREAD

**Issue by tanveer-hussain** [HwangJaeYoung/JaeYoung_PhD_Dissertation#1]
Hello, first of all, thank you for this nice repository, I was looking for Sejong university official LaTeX template, but wasn't able to find one, and here you've uploaded it, so it seems great.

Can you tell me from where you downloaded this? or is it all prepared by you? if it's prepared by you, was it accepted by the Department.

**Comment by HwangJaeYoung** [comment]
Hello,
When I asked about the dissertation format from Department, they said that they don't provide LaTeX format (Only provide .hwp and .doc officially). so I made the LaTeX format and used this but there was no problem. I think the Department doesn't care about the dissertation format strictly.

+) one of my colleagues in my lab (Sejong Univ) used this format for graduation this year and he passed.

**Comment by tanveer-hussain** [comment]
Ohh I see, thank you... this is a good help...
